require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'config/environments/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
