inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
