require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'config/environments/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/development.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/batch.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/values/container_profile.rb'
    - 'spec/support/stub_aspace.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/support/stub_aspace.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
