# frozen_string_literal: true

require "cgi"

# Emits the HTML that SimpleForm produced for this application's two forms.
#
# The Rails app used simple_form with the wrappers defined by
# config/initializers/simple_form_bootstrap.rb (generated by
# simple_form-bootstrap). Neither simple_form nor any other Rails-ecosystem
# library may be used here, so the handful of wrappers the forms actually
# referenced are reimplemented: :vertical_form (string/number/select inputs),
# :vertical_boolean (the generate_abid checkbox) and
# :horizontal_collection_inline (the ignore_size_validation radio buttons).
#
# Naming follows Rails' form builder exactly, because the specs address fields
# by name and id: "batch[first_barcode]" / "batch_first_barcode", and for
# nested attributes "marc_batch[absolute_identifiers_attributes][0][barcode]" /
# "marc_batch_absolute_identifiers_attributes_0_barcode".
module Abid
  class FormBuilder
    # SimpleForm's `config.error_method = :to_sentence`, and the `to_sentence`
    # the forms call on `errors[:base]`. ActiveSupport's implementation with the
    # default locale.
    def self.to_sentence(array)
      array = array.map(&:to_s)
      case array.length
      when 0 then ""
      when 1 then array[0]
      when 2 then "#{array[0]} and #{array[1]}"
      else "#{array[0...-1].join(', ')}, and #{array[-1]}"
      end
    end

    # CGI, not ERB::Util: ActiveSupport is in the bundle transitively and
    # patches ERB::Util.html_escape to skip strings marked html_safe, which is
    # exactly the wrong behaviour when escaping rendered markup into the
    # `data-association-insertion-template` attribute.
    def self.escape(value)
      CGI.escapeHTML(value.to_s)
    end

    attr_reader :object, :name_base, :id_base, :class_prefix

    def initialize(object:, name_base:, id_base:, class_prefix: nil)
      @object = object
      @name_base = name_base
      @id_base = id_base
      # SimpleForm's `generate_additional_classes_for` :wrapper adds
      # "#{model names joined}_#{attribute}" to every wrapper, which is what
      # `.marc_batch_absolute_identifiers_barcode` in the system spec matches.
      @class_prefix = class_prefix || id_base
    end

    # `f.simple_fields_for :absolute_identifiers` for one child record.
    def fields_for(association, index:, object:)
      self.class.new(
        object: object,
        name_base: "#{name_base}[#{association}_attributes][#{index}]",
        id_base: "#{id_base}_#{association}_attributes_#{index}",
        class_prefix: "#{class_prefix}_#{association}"
      )
    end

    def field_name(attribute) = "#{name_base}[#{attribute}]"

    def field_id(attribute) = "#{id_base}_#{attribute}"

    # SimpleForm's :vertical_form wrapper, used for string, number and select
    # inputs.
    def input(attribute, label:, as: "string", type: "text", input_class: nil, extra: {}, value: nil)
      value = object_value(attribute) if value.nil?

      field = tag(
        "input",
        {
          "class" => css(input_class, as, "form-control", invalid_class(attribute)),
          "type" => type,
          "value" => value.nil? ? nil : value.to_s,
          "name" => field_name(attribute),
          "id" => field_id(attribute)
        }.merge(extra)
      )

      vertical_wrapper(attribute, label: label, as: as, field: field)
    end

    # `f.input :attr, collection: ..., label_method: ..., value_method: ...`
    def select(attribute, label:, collection:, label_method:, value_method:)
      selected = object_value(attribute)

      options = [%(<option value="" label=" "></option>)]
      options += collection.map do |item|
        option_value = item.public_send(value_method)
        option_label = item.public_send(label_method)
        selected_attr = !selected.nil? && selected.to_s == option_value.to_s ? " selected=\"selected\"" : ""
        %(<option value="#{escape(option_value)}"#{selected_attr}>#{escape(option_label)}</option>)
      end

      field = %(<select class="#{escape(css('select', 'form-control', invalid_class(attribute)))}" ) +
              %(name="#{escape(field_name(attribute))}" id="#{escape(field_id(attribute))}">) +
              options.join +
              "</select>"

      vertical_wrapper(attribute, label: label, as: "select", field: field)
    end

    # SimpleForm's :vertical_boolean wrapper. The hidden field before the
    # checkbox is Rails' check_box pair, so unchecking submits "0".
    def boolean(attribute, label:)
      checked = truthy?(object_value(attribute))

      hidden = tag("input", "value" => "0", "autocomplete" => "off", "type" => "hidden", "name" => field_name(attribute))
      checkbox = tag(
        "input",
        "class" => css("boolean", "form-check-input", invalid_class(attribute)),
        "type" => "checkbox",
        "value" => "1",
        "checked" => checked ? "checked" : nil,
        "name" => field_name(attribute),
        "id" => field_id(attribute)
      )
      label_tag = %(<label class="boolean form-check-label" for="#{escape(field_id(attribute))}">#{escape(label)}</label>)

      <<~HTML
        <fieldset class="#{escape(css('form-group', 'boolean', wrapper_error_class(attribute), attribute_class(attribute)))}">
          <div class="form-check">
            #{hidden}
            #{checkbox}
            #{label_tag}
            #{full_error(attribute, 'invalid-feedback d-block')}
          </div>
        </fieldset>
      HTML
    end

    # SimpleForm's :horizontal_collection_inline wrapper with `label: false`.
    # `collection` is an array of [value, label] pairs.
    def radio_buttons(attribute, collection:)
      current = object_value(attribute)

      items = collection.map do |value, item_label|
        item_id = "#{field_id(attribute)}_#{value.to_s.gsub(/\W/, '_')}"
        radio = tag(
          "input",
          "class" => css("radio_buttons", "form-check-input", invalid_class(attribute)),
          "type" => "radio",
          "value" => value.to_s,
          "checked" => !current.nil? && current.to_s == value.to_s ? "checked" : nil,
          "name" => field_name(attribute),
          "id" => item_id
        )
        %(<div class="form-check form-check-inline">#{radio}) +
          %(<label class="collection_radio_buttons form-check-label" for="#{escape(item_id)}">#{escape(item_label)}</label>) +
          "</div>"
      end

      hidden = tag("input", "type" => "hidden", "name" => field_name(attribute), "value" => "", "autocomplete" => "off")

      <<~HTML
        <div class="#{escape(css('form-group', 'row', wrapper_error_class(attribute), attribute_class(attribute)))}">
          <div class="col-sm-9">
            #{hidden}
            #{items.join}
            #{full_error(attribute, 'invalid-feedback d-block')}
          </div>
        </div>
      HTML
    end

    # `f.input :attr, as: :hidden` - SimpleForm skips the wrapper entirely for
    # hidden inputs, so there is no wrapper div and no "form-control" class.
    def hidden(attribute, value: nil)
      value = object_value(attribute) if value.nil?
      tag("input", "value" => value.nil? ? nil : value.to_s, "autocomplete" => "off",
                   "type" => "hidden", "name" => field_name(attribute), "id" => field_id(attribute))
    end

    # Rails' `hidden_field_tag`, used for the CSRF token.
    def self.hidden_field_tag(name, value)
      %(<input type="hidden" name="#{escape(name)}" value="#{escape(value)}" autocomplete="off" />)
    end

    # `f.button :submit` - the value is Rails' "Create #{model.human_name}".
    def submit(value, css_class: "btn btn-primary")
      tag("input", "type" => "submit", "name" => "commit", "value" => value,
                   "class" => css_class, "data-disable-with" => nil)
    end

    # `f.error_notification message: ...`. SimpleForm renders nothing when the
    # object has no errors, and otherwise wraps the message in
    # `config.error_notification_tag` (:p) with the configured class.
    def error_notification(message: nil)
      return "" if object.nil? || object.errors.empty?

      message = base_errors_sentence if message.nil?
      %(<p class="alert alert-danger">#{escape(message)}</p>)
    end

    # `f.object.errors[:base].to_sentence`
    def base_errors_sentence
      self.class.to_sentence(object.errors[:base])
    end

    private

    def escape(value) = self.class.escape(value)

    def vertical_wrapper(attribute, label:, as:, field:)
      <<~HTML
        <div class="#{escape(css('form-group', as, wrapper_error_class(attribute), attribute_class(attribute)))}">
          <label class="#{escape(css(as, 'form-label'))}" for="#{escape(field_id(attribute))}">#{escape(label)}</label>
          #{field}
          #{full_error(attribute)}
        </div>
      HTML
    end

    # SimpleForm's :full_error component: the full messages for the attribute,
    # run through `config.error_method` (:to_sentence).
    def full_error(attribute, class_name = "invalid-feedback")
      messages = full_messages_for(attribute)
      return "" if messages.empty?

      %(<div class="#{class_name}">#{escape(self.class.to_sentence(messages))}</div>)
    end

    def full_messages_for(attribute)
      return [] if object.nil?

      object.errors.full_messages_for(attribute)
    end

    def error?(attribute) = !full_messages_for(attribute).empty?

    def invalid_class(attribute) = error?(attribute) ? "is-invalid" : nil

    def wrapper_error_class(attribute) = error?(attribute) ? "form-group-invalid" : nil

    def attribute_class(attribute) = "#{class_prefix}_#{attribute}"

    def object_value(attribute)
      return nil if object.nil? || !object.respond_to?(attribute)

      object.public_send(attribute)
    end

    def truthy?(value)
      case value
      when nil, false, "", "0", "false", "f", 0 then false
      else true
      end
    end

    def css(*classes)
      classes.compact.reject { |klass| klass.to_s.empty? }.join(" ")
    end

    def tag(name, attributes)
      rendered = attributes.filter_map do |key, value|
        next if value.nil?

        %( #{key}="#{escape(value)}")
      end.join

      "<#{name}#{rendered} />"
    end
  end
end
