defaults: &defaults
  archivespace_url: <%= ENV["ASPACE_URL"] || "https://aspace.princeton.edu/staff/api" %>
  archivespace_user: <%= ENV["ASPACE_USER"] %>
  archivespace_password: <%= ENV["ASPACE_PASSWORD"] %>

development:
  <<: *defaults

test:
  <<: *defaults
  archivespace_url: "https://aspace.test.org/staff/api"
  archivespace_user: "test"
  archivespace_password: "password"

production:
  <<: *defaults
  archivespace_url: <%= ENV["ASPACE_URL"] || "https://aspace.princeton.edu/staff/api" %>

staging:
  <<: *defaults
  archivespace_url: <%= ENV["ASPACE_URL"] || "https://aspace-staging.princeton.edu/staff/api" %>
